//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetId { get; set; }
        public decimal Limit { get; set; }
        public System.DateTime EffectiveStart { get; set; }
        public System.DateTime EffectiveEnd { get; set; }
        public int OfficeId { get; set; }
    
        public virtual Office Office { get; set; }
    }
}
