//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Memberships = new HashSet<Member>();
            this.HostedEvents = new HashSet<Event>();
            this.SponsoredEvents = new HashSet<Event>();
            this.EventsAttended = new HashSet<Event>();
        }
    
        public int PersonId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string BirthDate { get; set; }
        public string Nickname { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> ShirtSizeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneIsPublic { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Member> Memberships { get; set; }
        public virtual ICollection<Event> HostedEvents { get; set; }
        public virtual ICollection<Event> SponsoredEvents { get; set; }
        public virtual ICollection<Event> EventsAttended { get; set; }
        public virtual ShirtSize ShirtSize { get; set; }
        public virtual Address Address { get; set; }
    }
}
