//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShirtSize
    {
        public ShirtSize()
        {
            this.People = new HashSet<Person>();
        }
    
        public int ShirtSizeId { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
